### ISSUE TITLE
Has https://astroidframework.com/ been HACKED

### ISSUE THREAD

**Issue by ramblerswebs** [templaza/astroid-framework#166]
I see the one and zero versions of the template have a link to https://astroidframework.com/ in the footer

This keeps taking me to a Dating web site!!?

**Comment by Chacapamac** [comment]
Good observation @ramblerswebs 
**I just check and confirm the problem on both template Zero and One**

The problem is an old placeholder link belonging before to Joomdev that is set in the Copyright section of the template manager.

![Screen Shot 2022-08-08 at 9 44 44 AM](https://user-images.githubusercontent.com/1907276/183435222-81dcefe3-896b-4606-8168-e54d524ab7a5.jpg)

**I guess this old address website is now hacked or belong to this Wordpress dating web site?**

https://astroidframework.com/ need to be replaced by the new address —> https://astroidframe.work/

**Comment by sonvnn** [comment]
@ramblerswebs @Chacapamac Thank you for report issue. I moved astroidframework.com to astroidframe.work in Zero and One.

**Comment by ramblerswebs** [comment]
thanks

**Comment by Chacapamac** [comment]
Great!
