### ISSUE TITLE
Column Settings > Responsive > not allwed to change

### ISSUE THREAD

**Issue by Joomlaplates** [templaza/astroid-framework#246]
Hi everyone,
the column settings > responsive > Large
can not be changed. Its always "inherit". Is this a bug?
![Screenshot_2](https://user-images.githubusercontent.com/71080509/202903939-f7d639dd-22a1-42b2-983e-cb9371960105.jpg)

**Comment by Chacapamac** [comment]
Yes, Same here, seems to be a bug.
I mark it as a bug?

**Comment by sonvnn** [comment]
Hi @Joomlaplates

Thanks for report issue. I fixed this issue in https://github.com/templaza/astroid-framework/commit/3bfc988e96686211cec1fa9cd1490641a2d747c2

I assumed that Joomdev developer disable this select box because large design is default layout in Layout Builder. So they don't want to reconfigure double time.

Thanks & Best Regards,
Sonny
