### ISSUE TITLE
problem with page break plugin

### ISSUE THREAD

**Issue by SerGun78** [templaza/astroid-framework#422]
I recorded two videos that explain the problem.
Briefly. When you break a page set to accordion, they do not collapse back:
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/68a80a2b-a8ee-490e-babf-28a89f4d6fbc)
when switching to cassiopeia everything works:
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/5bea1372-9a75-4989-a962-af3c6cb04ed4)

**Comment by Chacapamac** [comment]
What code you use to make your accordion, Bootstrap?

**Comment by SerGun78** [comment]
no, this is a standard plugin from Joomla.

**Comment by Chacapamac** [comment]
This is probably the problem here. 
Maybe try to change what bootstrap is loaded in the Astroid plugin
![Screen Shot 2023-10-26 at 10 32 54 AM](https://github.com/templaza/astroid-framework/assets/1907276/94eb67be-9960-432c-8c8d-e96340d7b476)

Also, How Bootstrap build Accordion
https://getbootstrap.com/docs/5.2/components/accordion/

**Comment by SerGun78** [comment]
The standard "page break" plugin does not use bootstrap. In addition, in the astroid plugin I have js bootstrap completely disabled.

**Comment by SerGun78** [comment]
found the culprit. these are the js optimization and compression functions of the one template. It doesn't work correctly.
![изображение](https://github.com/templaza/astroid-framework/assets/95705148/d38f6e8c-f1c6-4aba-b8ec-ff655144058d)

**Comment by Chacapamac** [comment]
JS magnifying is always a hit and miss affair even with high-end software like JCH Optimize.
