### ISSUE TITLE
Social Icons - Freeze Up during search

### ISSUE THREAD

**Issue by AlisonAMG** [templaza/astroid-framework#497]
Just playing with Astroid Framework for the first time today. Thanks for the opportunity.
While filling in social network I noticed Mastodon was MIA. I did a search (in the search bar above the list) and the back end froze right the heck up. 
Does it use Font Awesome icons? If so can I just add in the appropriate code? 
Also, what's up with the link area. When trying to select the address it is the weirdest reaction I've ever come across. It jumps and shifts and makes it a heck of a time to just select part of what is there and add in your own details. Just a FYI on that.

**Comment by sonvnn** [comment]
Hi @AlisonAMG 

We are proud because you here. I glad to answer you questions below:

> While filling in social network I noticed Mastodon was MIA. I did a search (in the search bar above the list) and the back end froze right the heck up.

I test social search box and everything works well. May you detail your issue here?

> Does it use Font Awesome icons? If so can I just add in the appropriate code?

Yes, Astroid use Font Awesome and you can add custom social icon by click "Add Custom Profile" in the bottom of section.
![Screen Shot 2023-12-11 at 10 06 16](https://github.com/templaza/astroid-framework/assets/3204103/513cbba7-7f68-4bf7-a053-390e9171bea3)

> what's up with the link area. When trying to select the address it is the weirdest reaction I've ever come across.

Yes, I confirm this is an issue. I will improve it in 3.0.7

Thank you for your feedback! I hope you can stay here and have fun with Astroid

Best Regards,
Sonny

**Comment by sonvnn** [comment]
@AlisonAMG I fixed all issues related Social profile in commit https://github.com/templaza/astroid-framework/commit/95e47fc3b0fce73458d92bff1643bcb8e758fc8d

You can download dev version https://github.com/templaza/astroid-framework/archive/refs/heads/v3.zip and reupload to your site. Please let me know if this issue still happens

Thanks & Best Regards,
Sonny

**Comment by AlisonAMG** [comment]
Many thanks Sonny! Will check it out.
