### ISSUE TITLE
What is the Jollyany Framework and how it relate to Astroid?

### ISSUE THREAD

**Issue by Chacapamac** [templaza/astroid-framework#62]
**What is the Jollyany Framework and how it relate to Astroid?**

I went to “Join” on your site and what I see is that I get the **_“Jollyany | Multi-Purpose”_** for the price of the subscription.

**I personally want to Join to help in any way the development of Astroid.**

**I see nothing about Astroid here ?**
Remember that the “**Astroid**” framework gain a lot of notoriety at Joomla.
No offence, I never hear of the Jollyany Framework????

 —————————————————————————————
JUST SUGGESTIONS —————————————————————————————
_**Also, just my marketing view on that page:**_
-- For newbie on your site (like me), the “Jollyany | Multi-Purpose” product mean nothing.
-- Is it a framework, a template, what I’am getting with this subscription????  (All unanswered primordials questions)
-- You have no description of the product (s) that are included or even what are the terms and what exactly you get for that price, nothing????? 

**You need:**
-- A brief description of the product(s) and Services and advantages attached to this particular subscription
-- You need links to the details page of both included Product(s) (Jollyany | Multi-Purpose) & services & advantages related to the subscription

**I’m amaze that anybody buy that subscription...**

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

Jollyany Framework is an extended version of Astroid with UI Kit library. It's based on Astroid framework you can check it at https://github.com/templaza/jollyany

Thank you for your suggestion. I will update Jollyany description in the next update.

Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Just answer me when you have time.
I Just want to be sure to understand well what **Jollyany** is.

_**You Said:**_
_<<Jollyany Framework is an extended version of Astroid with UI Kit library>>_

Ok, Jollyany is based on Astroid and add a UI Kit Library. 
— I look at UI Kit libraries and, if I understand correctly, they are some kind of framework that specialized in interface building...
— I also see a lot of these UI Kit libraries (UIKIT, Fondation, others even use by Apple).

**Question:** 
_What are you using in Jollyany?_

**Question:** 
_What is the advantage of using another Framework (UI Kit) on top of Bootstrap ?_

**Comment by sonvnn** [comment]
Hi @Chacapamac ,

I am sorry for late reply.
Yes, Jollyany is an extend version based on Astroid. 

- It inherits all of Astroid functions
- Extend functions with UI Kit Framework https://getuikit.com/
- Included 65 SP Page Builder Addons
- Include TemPlaza template's system with 24 Joomla templates https://www.templaza.com/joomla-templates.html
- Re-style all of Hikashop layout based on UI Kit.

> Do you plan to merge Astroid and Jollyany together?

No, I don't. Jollyany is a project for TemPlaza user only. Astroid is a standalone project, I update it for Joomla Community.

> Can you remove All integration from Jollyany without problems.

Yes, You can. Jollyany just an extend library. It just required Astroid Framework to work only. You can remove SP Page Builder, TZ Portfolio, Hikashop or any other extension, even Astroid if you don't want to. Of course, you can use Jollyany + T4 Page Builder or other extension without any issue.

> About SP Page Builder Pro

I chose SP Page Builder because they have the biggest community. Almost requested by customers to use in their website. I have no choice. As a business person I have to serve the biggest piece of the pie.

> About JSN Page Builder

Their CEO is my friend in Vietnam. Most of their templates support my TZ Portfolio and we have a good friendship. I was sad when they closed Joomla and shifted focus to Shopify. But I respect their decision and they don't want to distribute their product as a free project that is the reason.

No idea about T4, Page Builder and Nextgen Editor as I haven't tried them. I will give you my ideas when I have a chance to test them

Thanks & Best Regards,
Sonny

**Comment by Chacapamac** [comment]
Hi @sonvnn 

Great, thank you for the clarification.

> I chose SP Page Builder because they have the biggest community. Almost requested by customers to use in their website. I have no choice. As a business person I have to serve the biggest piece of the pie.

I will do the same, I see that you include the PRO SP Page Builder version with your templaza subscription, I’m correct?

> Their CEO is my friend in Vietnam. Most of their templates support my TZ Portfolio and we have a good friendship. I was sad when they closed Joomla and shifted focus to Shopify. But I respect their decision and they don't want to distribute their product as a free project that is the reason.

That’s a shame, their Builder was a beautiful piece of work that was really using all the possibility and power of Joomla

> No idea about T4, Page Builder and Nextgen Editor as I haven't tried them. I will give you my ideas when I have a chance to test them

I’m testing all of these from time to time to see where they going, I will test again SP Page Builder...

You can close this discussion
Thank You again and Good day!

**Comment by rinka88** [comment]
but why spawn such a monster with both bootstrap and uikit and sp page builder (it has its own bootstrap monster)

**Comment by Chacapamac** [comment]
Just thinking!
• Bootstrap is included with Joomla, we can use it without adding anything
• Today a CMS without a WYSIWYG Drag & Drop Editor is doom to disappear. Even Wordpress was smart enough to build their somewhat crappy Gutenberg to secure their futur
— I even made that post for Joomla —> https://forum.joomla.org/viewtopic.php?f=575&t=988600 (2130 views and going up) on how it’s primordial that Joomla do their own Editor to ensure top integration and top efficiency. Sadly, when you let somebody else building on of the most important motor in a CMS by whoever you end-up with bloated stuff that don’t even respect the full power of Joomla like SP Page Builder
— Sony choose SP because its the biggest fish in the pond and great Joomla friendly Editor, like JSN PageBuilder go dow in flame because people go for light that flash and don’t take the time to see what is around them.
— Also it’s an editor, if you don’t like it, you can choose anything you fancy.

I’m not really knowledgeable with UIKIT, but as I check, it seem to be low impact, seem cooler, friendlier to use than Bootstrap that can be a pain in the ----- , relatively low impact, and full of cool stuff that Bootstrap cannot do.

Personally I always use some external small librairies to do animations and few others things important to me.

Also, Astroid is a extremely fast framework to start on. You have room to have fun...

**Comment by Chacapamac** [comment]
Thanks Sonny for the Clear explanation
