### ISSUE TITLE
How to handle override information on updates in the right way

### ISSUE THREAD

**Issue by djayko** [templaza/astroid-framework#76]
Hello,

after last update today I figured out some "overrides to check" within joomla 4. 
There are 5 checks per astroid template.

I guess it would be ok skipping that infomation by marking this overrides as checked, rright?
Otherwise, what should a "standard user" do if he/she is using astroid templates?

best regards,
Ayko

**Comment by sonvnn** [comment]
Hello @djayko,

It's Joomla feature notices you that some files was changed when you update an extension. It's obvious, because if you don't change anything, there's nothing to update. Many customer asked me about this bullshit from Joomla =))

Best Regards,
Sonny

**Comment by djayko** [comment]
Hi @sonvnn Sonny,

I guess this information is really useful to check, if joomla is changing something which could have affects to a template.
But I also understand it's not necessesary for "standard" customers to understand. 

Maybe it would help having some kind of FAQ for how to handled it -> like "don't worry, ignore this warning or open the templates and mark the overrides as checked."

Best Ayko

**Comment by sonvnn** [comment]
Hi @djayko,

It's Joomla core feature. You can suggest this feature to them on https://github.com/joomla/joomla-cms/issues

Best Regards,
Sonny

**Comment by djayko** [comment]
Hi @sonvnn,
Don't get me Wrong, this information is an information from joomla about the overrides created by astroid and how they differ from the core, right? 
And need to be handled on template creation side not.

Maybe I have a different understanding what this information is for and I missunderstood your point regarding an information towards joomla core.

best,
Ayko

**Comment by sonvnn** [comment]
Hi Ayko,

Joomla notification because this code from Astroid https://github.com/templaza/astroid-framework/blob/master/framework/library/astroid/Helper/Overrides.php#L40:L46

Joomdev's devs want to remove old files from their templates. They rename them to another to avoid Template override Joomla core extensions. May be they are out of date. 

This code is use when customer update their template, only. I will remove this code in v2.5.14. So you will not worry about Override notifications from Joomla anymore :) 

I don't comment about Joomla Feature. Because some users don't understand about it and ask me about them. Personally, I don't like having to explain over and over an issue that doesn't affect their site. One of my clients asked for a refund just because of this message from Joomla. I assumed that why I don't like this feature. =))

Thanks & Best Regards,
Sonny
