### ISSUE TITLE
The update 2.5.6 threw an error

### ISSUE THREAD

**Issue by kkaazzoo** [templaza/astroid-framework#8]
Hi, the update threw an error

Error: "#adminForm .controls" failed to @extend ".form-group". The selector ".form-group" was not found.: libraries/astroid/framework/library/astroid/./../../../../../templates/astroid_template_zero/scss/zero/style.scss on line 68, at column 3: "#adminForm .controls" failed to @extend ".form-group". The selector ".form-group" was not found.: libraries/astroid/framework/library/astroid/./../../../../../templates/astroid_template_zero/scss/zero/style.scss on line 68, at column 3 

![image](https://user-images.githubusercontent.com/19167244/140299553-64650ce3-b782-4cca-b922-441e5188bcdb.png)

**Comment by sonvnn** [comment]
Bootstrap 5 drop support .form-group
"Dropped form-specific layout classes for our grid system. Use our grid and utilities instead of .form-group, .form-row, or .form-inline."
https://getbootstrap.com/docs/5.0/migration/

Please wait for update version. I will test with Zero template in next few days.

Best Regards,
Sonny

**Comment by Joomlaplates** [comment]
Just a quickfix, rename the file
`../scss/style.scss` to `../scss/style.scss_bak`

**Comment by sonvnn** [comment]
Hi @kkaazzoo 
I fixed your issue at #9 
You can download / update v2.5.7 to fix your issue. I tested with both of 2 free template and they works like a charm.

Please let me know if you find any-issue further.

Best Regards,
Sonny

**Comment by kkaazzoo** [comment]
Hi, @sonvnn!
Thank you, problem solved!
