### ISSUE TITLE
Astroid 3.1.7 scroll speed setting is no longer there

### ISSUE THREAD

**Issue by WM-Loose** [templaza/astroid-framework#851]
The scroll speed setting is no longer there.
![1](https://github.com/user-attachments/assets/38dc4e42-81c0-46e4-b97c-c0370fa45937)

**Comment by Joomlaplates** [comment]
The site scroll in so slow when the Smoóth Scroll is acivated.
![smoothscroll](https://github.com/user-attachments/assets/67c1952c-3758-45b5-b721-9e257978c0d8)
Regards Peter

**Comment by sonvnn** [comment]
@WM-Loose @Joomlaplates I replaced Polyfill with Lenis js. Polyfill has been unmaintained for 4 years now. Lenis is considered the best Smooth Scroll at the moment. So I chose it as the best solution. However, since it is 2 different JS. The settings have also been changed and you need to clear Astroid Cache for the website to receive the latest Lenis style. You can learn more about Lenis here https://lenis.darkroom.engineering/

**Comment by Joomlaplates** [comment]
Hi Sonny, clean cache is not solving the problem.
If smooth scroll is active the whole page scrolls like a retired person.
I mean the general website scriollbar in the Browser when you scroll down with the mouse.
Regards Peter

**Comment by sonvnn** [comment]
@Joomlaplates I just updated Astroid 3.1.7 and Astroid Pro on https://astroidframe.work/ And it works smoothly. 
Can you help me clear cache, browser cache and server cache? If it is still happen, please send me your url. I will help you check it.

Best regards,
Sonny

**Comment by sonvnn** [comment]
@Joomlaplates Your site is working like a charm. I don't see any issue here
[Home (3).webm](https://github.com/user-attachments/assets/37011014-10e1-4448-b261-ba0aea6bb510)

**Comment by sonvnn** [comment]
Hi @WM-Loose 
I brought this option back in v3-branch. Please help me download v3-branch and retest it again.

Best Regards,
Sonny
