### ISSUE TITLE
Overflow with mousewheel

### ISSUE THREAD

**Issue by fontanil** [templaza/astroid-framework#863]
**Describe the bug**
Use an extension for download files, like Phoca download

**To Reproduce**
Open a page for download (for example https://www.joomxtensions.com/en/component/phocadownload/file/49-moovjla-2021-06-01.html?catid=1:utilitaires&Itemid=131 )
Try to scroll over the licence text: all the window scroll, not only the content of the text area

**Expected behavior**
Text scrolls with mouse wheel (works with Cassiopeia)

**System Informations (please complete the following information):**
 - Joomla Version: 5.2.1
 - PHP Version 8.2.21
 - Astroid Version 3.1.17
 - Device: PC
 - OS: Windows 11
 - Browser tested on Firefosx ans Chrome last versions

**Comment by sonvnn** [comment]
This is an issue when you enable Smooth-Scrolling. Because we are using Lenis smooth scrolling. 
The solution below:
1. Disable Smooth-Scroll in the template options 
2. Add `data-lenis-prevent` attribute to `<div id="phoca-dl-license" style="height:300px">`. Try `<div id="phoca-dl-license" data-lenis-prevent="" style="height:300px">` refer https://github.com/darkroomengineering/lenis/discussions/242

**Comment by fontanil** [comment]
Thanks Sonny!

I disabled Smooth scrolling and now I can scroll with the mouse wheel, without applying the second part of your solution.
Regards,
